PACKAGE_JSON = "package.json"
SERVERLESS_YML = "serverless.yml"
ONBOARDED_REPOS = "onboarded_repos.json"
REQUIREMENTS_TXT = "requirements.txt"
REQUIREMENTS_FULL_PATH = f"functions/{REQUIREMENTS_TXT}"
SOCLESS_PYTHON_PIP_PATTERN = r"(.+socless_python.git)(@[.\d]+#)(egg=socless)"
